# config.yaml
# Edit these paths and options for your basin / domain.

# -------------------------------------------------------------------
# Coordinate system and grid
# -------------------------------------------------------------------
crs_epsg: "EPSG:32612"        # Desired output CRS
target_res_m: 100.0           # Output grid resolution (m)
bbox_expand_pct: 0.0          # Total fractional expansion of rectangular bbox (0.20 â‰ˆ 10% each side)

# -------------------------------------------------------------------
# Input paths
# -------------------------------------------------------------------
dem_path: "Example_input_data/PackTrail_DEM.tif" # Make sure you unzip the file first if using example data, otherwise replace with your file name/ location
shape_path: "Example_input_data/PackTrail_Per.shp"
veg_h_tif_path: "Example_input_data/PackTrail_GEDI_VegH"
lai_path: "Example_input_data/PackTrail_LAI07072025.tif"
nlcd_tif_path: "Example_input_data/PackTrail_NLCD24.tif"

# -------------------------------------------------------------------
# Output
# -------------------------------------------------------------------
save_output: true
out_nc_path: "New_topo.nc"

# -------------------------------------------------------------------
# Resampling choices
# -------------------------------------------------------------------
resample_continuous: "bilinear"  # veg height & LAI
resample_categorical: "nearest"  # NLCD (categorical)

# -------------------------------------------------------------------
# QC / limits
# -------------------------------------------------------------------
vh_max_to_keep: 25.0      # m; > this -> set to 0 (removes unrealistic veg height near water)
lai_scale: 3.0            # undo LAI symbology scaling from Copernicus site (only if downloading directly from data viewer using this product). Set to 1 otherwise. 
lai_floor: 0.001          # Min LAI to avoid log(<=0) / div-by-zero

# -------------------------------------------------------------------
# Veg k & tau settings
# -------------------------------------------------------------------
zero_tau_types: [11, 12, 21, 22, 23, 24, 31, 51, 52, 71, 72, 73, 74, 81, 82, 90, 95, 92]  #NLCD canopy types set to tau = 0, k =1
use_fixed_decid_mixed: true

deciduous_41_k: 0.025
deciduous_41_tau: 0.44

mixed_43_k: 0.033
mixed_43_tau: 0.30

